name: Fetch Contributions

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch GitHub contribution calendar
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          mkdir -p data

          gh api graphql \
            -f query='
              query($login: String!) {
                user(login: $login) {
                  contributionsCollection {
                    contributionCalendar {
                      totalContributions
                      weeks {
                        contributionDays {
                          date
                          contributionCount
                          contributionLevel
                          color
                          weekday
                        }
                      }
                    }
                  }
                }
              }
            ' \
            -f login='diptim06' \
            > data/contributions.json

      - name: Save contribution data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/contributions.json

          git diff --cached --quiet || \
            git commit -m "Update contribution data"

          git push